### ISSUE TITLE
HTTP header uber-trace-id has multiple values in case Apache HTTPClient is used as underlying implementation of Spring's RestTemplate 

### ISSUE THREAD

**Issue by 617m4rc** [opentracing-contrib/java-apache-httpclient#11]
In its default configuration, the SpecialAgent injects the uber-trace-id header into RestTemplate via the Spring Web instrumentation plugin. Later, the Apache HttpClient plugin injects a different value for the same HTTP header and request. These multiple values can lead to severe problems on the receiving end, in particular, when using the Jaeger Tracer plugin that enforces exactly one value. 

An additional check in class HttpHeadersInjectAdapter should ensure that there is not already a header with the same name (but possibly different value).

**Comment by IndicatorFluid** [comment]
The easiest workaround for this I found is having a custom fake span decorator that removes duplicate headers. 
This is also specific to Jaeger:

```
public class HeaderDeduplicatingSpanDecorator implements ApacheClientSpanDecorator {
    @Override
    public void onRequest(HttpRequestWrapper request, HttpContext httpContext, Span span) {
        // This is somewhat a hack, using span decorator to modify request headers.
        // This is also specific to Jaeger that uses uber-trace-id.
        //
        // See: https://github.com/opentracing-contrib/java-apache-httpclient/issues/11
        Header[] headers = request.getHeaders("uber-trace-id");
        if (headers.length > 1) {
            request.removeHeaders("uber-trace-id");
            request.setHeader(headers[headers.length - 1]);
        }
    }

    @Override
    public void onResponse(HttpResponse response, HttpContext httpContext, Span span) {
    }

    @Override
    public void onError(HttpRequest request, HttpContext httpContext, Exception ex, Span span) {
    }
}
```
