### ISSUE TITLE
NPE if URL does not have a scheme

### ISSUE THREAD

**Issue by AudriusButkevicius** [opentracing-contrib/java-apache-httpclient#18]
I have observed an exception in a production system on the following line:

https://github.com/opentracing-contrib/java-apache-httpclient/blob/2202f0b270a09471242b9d548a2a01d25c3e61fc/opentracing-apache-httpclient/src/main/java/io/opentracing/contrib/apache/http/client/ApacheClientSpanDecorator.java#L71

It seems that getSchemeName can return null, at which point the tracing breaks the request.

**Comment by pavolloffay** [comment]
hi @AudriusButkevicius thanks for reporting. Would you like to submit a fix?
