### ISSUE TITLE
Question Not an Issue: Does anybody knows if there is any opentracing support for Java HttpClient ?

### ISSUE THREAD

**Issue by ghevge** [opentracing-contrib/java-apache-httpclient#23]
Does anybody knows if there is any opentracing support for Java HttpClient introduced in Java 11?

https://openjdk.java.net/groups/net/httpclient/intro.html

Thanks

**Comment by pavolloffay** [comment]
I don't know about it, please raise an issue in https://github.com/open-telemetry/opentelemetry-java-instrumentation
